DeveloperAcademy-POSTECH/MC2-Team14-OXY

- TeamOXY/TeamOXY.xcodeproj/project.pbxproj
- View: SwiftUI & UIKit View 파일을 관리하는 폴더
- ViewModel: ViewModel 폴더
- Model: Model 폴더
- Extension: Extension 코드 파일을 관리하는 폴더
- Constant: 이미지 이름, Color 등 상수들을 관리하는 폴더
- 프로젝트 폴더 구조 잡았음.
> #2 Config: 프로젝트 폴더 구조 설정

- TeamOXY/TeamOXY.xcodeproj/project.pbxproj
- TeamOXY/TeamOXY/View/EmojiReactionView.swift
- TeamOXY/TeamOXY/View/FancyButtonViewModel.swift
- TeamOXY/TeamOXY/View/TestView.swift
- 가로 스크롤 가능한 이모지 선택 View 구현
- 이모지 버튼을 누를 시 화면 가운데에서 애니메이션 작동 
- 다른 이모지 버튼을 눌렀을 때 기존의 애니메이션이 끊기는 현상
- 이모지 버튼을 선택 시 이모지가 log 에 잘 뜨는지 확인
좋은 UX 를 경험할 수 있는 애니메이션이 있다면 알려주세요!
구조체 에서 프로퍼티를 수정할 수 있는 좋은 방법이 있다면 알려주세요!
직접 이모지를 적지 않고 변수명으로 화면을 교체할 수 있는 방법을 알려주세요!
https://github.com/simibac/ConfettiSwiftUI
> [Merge] #12 반응 이모지 애니메이션 구현

- TeamOXY/TeamOXY.xcodeproj/project.pbxproj
- TeamOXY/TeamOXY/Components/RoundButton.swift
- TeamOXY/TeamOXY/Constants/FieldType.swift
- TeamOXY/TeamOXY/View/CreateMeetingRoomView.swift
- TeamOXY/TeamOXY/View/HomeView.swift
- CreateMeetingRoomView UI
- 뷰 접근 시 TextField 활성화
- TextField 키보드 세부 설정
- 자동 대문자 취소
- 자동 수정 취소
- 뷰 접근 시 TextField 활성화를 위해 FocusState 활용 -> 추후 확장성을 고려한 포인트이긴 하지만 지금 단계에서 굳이? 일 수도 있습니다.
- https://developer.apple.com/documentation/swiftui/focusstate
> [Merge] #37 CreateMeetingRoomView UI

- TeamOXY/TeamOXY.xcodeproj/project.pbxproj
- TeamOXY/TeamOXY/View/QRCode/QRCode.swift
- TeamOXY/TeamOXY/View/QRCode/QRCodeView.swift
- QR Code 생성 함수 구현
- QRCodeView UI Design
- CIFilter.qrCodeGenerator() 를 활용해서 QR Code 생성 함수 구현
- QR Code에 해당 MeetingRoom urlScheme 연결을 어떻게 해야할까요?
- https://developer.apple.com/documentation/coreimage/cifilter
- https://developer.apple.com/documentation/coreimage/cifilter/3228262-qrcodegenerator
> [Merge] #39 QRCodeView UI

- TeamOXY/TeamOXY.xcodeproj/project.pbxproj
- TeamOXY/TeamOXY/TeamOXYApp.swift
- TeamOXY/TeamOXY/View/EmojiReactionView.swift
- TeamOXY/TeamOXY/ViewModel/EmojiViewModel.swift
- 중복 가능하게 반응 애니메이션 구현
- 카드를 아래로 제스처 할 수 있다는 화살표 VIew 추가
- 반응 버튼을 여러개 눌러도 기존의 애니메이션을 사라지지 않음
- 카드를 아래로 제스처 할 수 있다는 화살표에 애니메이션을 추가해야 할까요?
- 스케치의 텍스트 크기로 하게되면 텍스트가 너무 작아지는데 어떻게 할까요? ( 현재 시스템 기본 크기 )
https://github.com/simibac/ConfettiSwiftUI
> [Merge] #36 중복 가능한 반응 애니메이션 구현

- TeamOXY/TeamOXY.xcodeproj/project.pbxproj
- TeamOXY/TeamOXY/View/BreakTimeView.swift
- TeamOXY/TeamOXY/View/CircularTimerView.swift
- TeamOXY/TeamOXY/View/TimeSetView.swift
- TeamOXY/TeamOXY/View/Timer/BreakTimeView.swift
- TeamOXY/TeamOXY/View/Timer/CircularTimerView.swift
- TeamOXY/TeamOXY/View/Timer/TimeSetView.swift
timerView 추가
지난 번 머지에서 타이머뷰가 누락됐습니다
연결 진행 중 입니다. 
깃...
> [merge] #45 timer view update

- TeamOXY/TeamOXY.xcodeproj/project.pbxproj
- TeamOXY/TeamOXY/View/BreakTimeView.swift
- TeamOXY/TeamOXY/View/CircularTimerView.swift
- TeamOXY/TeamOXY/View/TimeSetView.swift
> [Merge] #45 TimerViewUI

- TeamOXY/TeamOXY.xcodeproj/project.pbxproj
- TeamOXY/TeamOXY/View/FinishTopicView.swift
- 타이머 설정 여부를 묻는 FinishTopicView UI를 구현했습니다.
- 프로토타입과 다른 부분이 있는지
- 코드 정리
- MeetingRoomView와 합치기
- 커스텀 폰트 적용하기
- 아이콘을 Text로 설정한 부분을 어떻게 개선할 지
> [Merge] #46 FinishTopicView UI 구현

- TeamOXY/TeamOXY.xcodeproj/project.pbxproj
- TeamOXY/TeamOXY/View/CreateMeetingRoomView.swift
- TeamOXY/TeamOXY/View/HomeView.swift
- TeamOXY/TeamOXY/View/QRCode/QRCode.swift
- TeamOXY/TeamOXY/View/QRCode/QRCodeView.swift
- QRCodeScanner이 HomeView의 입장하기 버튼을 누르면 동작하도록 로직 구현
- QRCodeView의 qrCode(forKey: )에 "inputMessage"가 들어가도록해야 작동한다. -> 아직 정확한 이유는 모름.
- 카메라에 접근해서 qr code scan하는데 닫기 버튼을 ZStack을 활용했는데 이렇게 하는게 맞는건지 모르겠다.
- https://medium.com/swlh/build-your-qr-code-reader-7b89ca401e9a
> [Merge] #56 QRCodeScanner 구현

- TeamOXY/TeamOXY.xcodeproj/project.pbxproj
- TeamOXY/TeamOXY/View/Arrows.swift
- TeamOXY/TeamOXY/View/EmojiReactionView.swift
- TeamOXY/TeamOXY/ViewModel/EmojiViewModel.swift
- 카드를 잡고 내리거나 올릴 수 있는 가이드 애니메이션 추가
- 애니메이션이 잘 작동하는지 확인
- 색상과 투명도가 잘 이루어졌는지 확인
- 카드를 올릴 때도 해당 가이드가 필요할까요?
https://stackoverflow.com/questions/60852328/swiftui-animation-how-to-stagger-repeating-animation-with-delay
> [Merge] #59 argument guide animation 구현

- TeamOXY/TeamOXY/Assets.xcassets/Button_LeaveRoom.imageset/Button_LeaveRoom.svg
- TeamOXY/TeamOXY/Assets.xcassets/Button_LeaveRoom.imageset/Contents.json
- TeamOXY/TeamOXY/View/CarouselView.swift
- TeamOXY/TeamOXY/View/EmojiReactionView.swift
- TeamOXY/TeamOXY/View/FinishTopicView.swift
- TeamOXY/TeamOXY/View/MeetingRoomView.swift
- FinishTopicView 연결
- 이모지뷰, 카드뷰 상황따라 다르게 나오게 구현
- 미팅룸에 카드 올려놓는 네모박스
- confirmationDialogue 수정
- FinishTopicView를 띄우는 로직을 배열에 어떤 요소가 연속으로 나오냐?로 구현을 했는데 컴파일 에러를 안나게 하려고
default array(FInishTopicViewCondition 프로퍼티)에 false를 미리 두 개를 넣어놨는데,, 이 로직이 마음에 안듭니다.
- 니로가 올려주신 로티와 화살표 미팅룸에 합치기
- 로직에 대한 설명 주석으로 추가하기
- 미팅룸에 점선 네모박스 추가했는데 더 좋은 디자인이 있으면 알려주세요!
> [Merge] #58 미팅룸뷰 합치기 (conflict 날 것 같아서 니로, 다니, 데이크가 같이 머지하는게 좋을 것 같습니다.)

- TeamOXY/TeamOXY.xcodeproj/project.pbxproj
- TeamOXY/TeamOXY/TeamOXYApp.swift
- TeamOXY/TeamOXY/View/CarouselView.swift
- TeamOXY/TeamOXY/View/EmojiReactionView.swift
- TeamOXY/TeamOXY/View/FinishTopicView.swift
- TeamOXY/TeamOXY/View/TopicCompletionView.swift
- TeamOXY/TeamOXY/ViewModel/CompletionViewModel.swift
- 중복된 텍스트가 겹치면서 캐러셀이 밀리는 현상 수정
- 니로가 보내준 컴플리션 로티 FinishTopicView에 연결
- 로티뷰를 띄워줄 viewModel 생성
- 애니메이션을 임의로 추가하긴 했는데 인터랙션이 자연스러운지 확인 부탁드립니다.
- Carousel 뷰가 많이 무겁습니다.. 
- 인터랙션 수정사항 있으면 반영할 예정
- Carousel뷰 코드 정리
> [Merge] #64 캐러셀버그수정 & 컴플리션로티추가

- TeamOXY/TeamOXY.xcodeproj/project.pbxproj
- TeamOXY/TeamOXY/TeamOXYApp.swift
- Firebase cloud messaging 연동 및 노티 수신 확인
> [Merge] #67 Firebase Messaging & Functions

- TeamOXY/TeamOXY.xcodeproj/project.pbxproj
- TeamOXY/TeamOXY/Model/Reaction.swift
- TeamOXY/TeamOXY/Model/Topic.swift
- TeamOXY/TeamOXY/Model/User.swift
- User 데이터 모델 생성
- uid, nickname, documentId
- Topic 데이터 모델 생성
- Reaction 데이터 모델 생성
- fromId, toId, reaction, documentId
- ex) "reactions" > fromId > toId > document field
- 데이터 모델을 생성할 때, 네트워킹을 고려해서 data를 initializer에서 파라미터로 받아서 값을 초기화한다.
> [Merge] User, Topic , Reaction 데이터 모델 생성

- TeamOXY/TeamOXY.xcodeproj/project.pbxproj
- TeamOXY/TeamOXY/Constants/FirebaseConstants.swift
- TeamOXY/TeamOXY/Utils/FirebaseManager.swift
- TeamOXY/TeamOXY/Utils/generateRandomNickname.swift
- FirebaseManager 생성
- FirebaseAuth 연결
- FirebaseFirestore 연결
- FirebaseConstants 생성
- fromId
- toId
- topicTitle
- reaction
- timestamp
- generateRandomNickname 함수 생성
- 랜덤 닉네임 생성
- 사용자 직접 입력 시 최대 3글자까지 허용. 그 이후로 글자 잘림
- FirebaseManager에 FirebaseAuth, Firestore 연결
> [Merge] #73 Firebase 환경 설정

- TeamOXY/TeamOXY.xcodeproj/project.pbxproj
- TeamOXY/TeamOXY/Extensions/TypographyExtension.swift
- Typography Extension 생성
```swift
ex)
Text("Hello, world!")
.headLine1()
```
- https://sketch.com/s/8a6146a8-3b22-4c82-b386-596ed7cef2d6
> [Merge] #66 Typography Extension 생성

- TeamOXY/TeamOXY/View/TestCardView.swift
- 'animation' was deprecated 오류를 수정하였습니다
- 카드가 올라가고 내려올 때 자연스럽게 크기가 커지고 작아지도록 수정했습니다
- 전체적으로 코드를 정리하고 읽기 쉽도록 변수명 변경, 주석 달기 등의 작업을 하였습니다
- 충돌을 피하기 위해 겹치는 변수명은 수정해서 올렸습니다
- 크기가 커지고 작아지는 인터랙션이 자연스러운 지 확인 후 선택적으로 CarouselView에 반영 부탁드립니다
- 최대한 누구나 이해하고 재사용 할 수 있도록 주석을 열심히 써 보았는데, 아직 부족한 점이 있다면 편하게 수정요청 해주세요!
- 변수명 이해를 돕기 위해 사진을 첨부합니다
> [Merge] #75 TestCardView 리팩토링 및 오류 수정

- TeamOXY/TeamOXY.xcodeproj/project.pbxproj
- TeamOXY/TeamOXY/TeamOXYApp.swift
- TeamOXY/TeamOXY/Utils/FirebaseManager.swift
- TeamOXY/TeamOXY/Utils/generateRandomNickname.swift
- TeamOXY/TeamOXY/View/CreateMeetingRoomView.swift
- TeamOXY/TeamOXY/View/Home/HomeView.swift
- TeamOXY/TeamOXY/View/MeetingRoom/MeetingRoomView.swift
- TeamOXY/TeamOXY/ViewModel/MeetingRoomViewModel.swift
- 방 입장 시, 익명 로그인
- 유저 정보 Firestore에 저장
- MeetingRoom에 접근하여 익명 로그인 후, 유저 정보를 저장하는 로직
> [Merge] 방 생성 익명 로그인, 유저 정보 Firestore에 저장

- TeamOXY/TeamOXY.xcodeproj/project.pbxproj
- TeamOXY/TeamOXY/Constants/FirebaseConstants.swift
- TeamOXY/TeamOXY/Model/MeetingRoom.swift
- TeamOXY/TeamOXY/View/MeetingRoom/MeetingRoomView.swift
- FirebaseFirestore collection and document depth
> [Merge] #79 FirebaseFirestore collection and document depth

- TeamOXY/TeamOXY/Components/RoundButton.swift
- TeamOXY/TeamOXY/Extensions/String+ButtonImageName.swift
- TeamOXY/TeamOXY/Extensions/TypographyExtension.swift
- TeamOXY/TeamOXY/View/BreakTime/BreakTimeView.swift
- TeamOXY/TeamOXY/View/BreakTime/CircularTimerView.swift
- TeamOXY/TeamOXY/View/BreakTime/TimeSetView.swift
- TeamOXY/TeamOXY/View/CreateMeetingRoomView.swift
- TeamOXY/TeamOXY/View/Home/HomeView.swift
- TeamOXY/TeamOXY/View/Home/QRCode/QRCodeView.swift
- TeamOXY/TeamOXY/View/MeetingRoom/EmojiReactionView.swift
- TeamOXY/TeamOXY/View/MeetingRoom/FinishTopicView.swift
- TeamOXY/TeamOXY/View/MeetingRoom/MeetingRoomView.swift
리팩토링
- Typography 적용
- 공용 컴포넌트 적용
- TypoExtension 활용
- RoundButton 활용
> [Merge] #91 리팩토링: Typography 적용 및 공용 컴포넌트 적용

- TeamOXY/TeamOXY.xcodeproj/project.pbxproj
- TeamOXY/TeamOXY/View/MeetingRoom/CarouselView.swift
- Ref: #103
- card덱에서 센터카드가 아닌 다른 카드를 선택했을 때 햅틱 & 롱프레스드래그 되는 현상 수정
- 다른 카드에서는 햅틱 & 롱프레스드래그 안되는지 확인부탁드립니다.
> [fix] Carddeck의 버그 수정

- TeamOXY/TeamOXY/View/MeetingRoom/CarouselView.swift
- TeamOXY/TeamOXY/View/MeetingRoom/EmojiReactionView.swift
- TeamOXY/TeamOXY/View/MeetingRoom/MeetingRoomView.swift
- TeamOXY/TeamOXY/ViewModel/EmojiViewModel.swift
- `MeetingRoomView` , `CarouselView` , `EmojiReactionView` 에 EmojiViewModel 추가 
- 위 3개의 View는 `emojiViewModel` 로 연결
- EmojieViewModel 에서 EmojiViewModel 로 이름 변경
- `MeetingRoomView` , `CarouselView` , `EmojiReactionView` 에 `EmojiViewModel` 추가
> [Merge] #106 CarouselView 의 Card 를 누를시 발생하는 Reaction Animation 수정

- TeamOXY/TeamOXY/Extensions/String+ButtonImageName.swift
- TeamOXY/TeamOXY/TeamOXYApp.swift
- TeamOXY/TeamOXY/View/BreakTime/BreakTimeView.swift
- TeamOXY/TeamOXY/View/BreakTime/TimeSetView.swift
TimeSetView, BreakTimeView UI 수정
picker refactor
picker refactor 한 부분 확인부탁드립니다.
> [Merge] #94 time set view update

- TeamOXY/TeamOXY/View/BreakTime/TimeSetView.swift
> Feature/#110 timeSetView UI 

- TeamOXY/TeamOXY/View/CreateMeetingRoomView.swift
- TeamOXY/TeamOXY/View/MeetingRoom/CarouselView.swift
- TeamOXY/TeamOXY/View/MeetingRoom/EmojiReactionView.swift
- TeamOXY/TeamOXY/View/MeetingRoom/MeetingRoomView.swift
- TeamOXY/TeamOXY/ViewModel/EmojiViewModel.swift
- Reaction Emoji 요소와 개수를 수정 ( 15 -> 10개 )
- Reaction Emoji Animation 으로 보이는 Emoji 의 수와 크기 조절 ( 5 -> 3개, 30 -> 40 )
- `AnonymousLoginLoadingView()` 로드 시 보이는 BackButton 삭제
- `MeetingRoomView` 에서 `CarouselView` 선언 시 빠져있는 파라미터 값 추가
- `CarouselView` 에서 `EmojiReactionView` 선언 시 빠져있는 파라미터 값 추가
- 이모지 리액션의 크기와 개수 등 잘 어울리는지 확인
- 방만들고 안건 던지는 View 로 전환시 나오는 Loading 화면에서 뒤로가기 버튼이 없어졌는지 확인
> [Merge] #122 Reaction Emoji Animation 수정 및 BackButton 삭제
